### ISSUE TITLE
Plugin does not work in digdag 0.10.0

### ISSUE THREAD

**Issue by gumigumi4f** [civitaspo/digdag-operator-param#10]
Plugin does not work in digdag 0.10.0 due to using deprecated digdag api.
Error message is below.
```
Task failed with unexpected error: 'java.lang.String io.digdag.util.Workspace.createTempFile(java.lang.String, java.lang.String)'
java.lang.NoSuchMethodError: 'java.lang.String io.digdag.util.Workspace.createTempFile(java.lang.String, java.lang.String)'
```

It seems that it is already been fixed by #9.

**Comment by civitaspo** [comment]
Fixed in [v0.0.3](https://github.com/civitaspo/digdag-operator-param/releases/tag/0.0.3).
